<a href="https://colab.research.google.com/github/cestsuperwin59/data-science-bootcamp/blob/main/Essential_python_for_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# super class
class Person:
    def __init__(self, name):
        self.name = name
    def hey(self):
        print("Hello world")
    def sayhi(self):
        print(f"Hi my name is {self.name}!")

class Employee(Person): #superclass -> upgrade from person and has new method sayhi
    def __init__(self, name, company):
        super().__init__(name)
        self.company = company
    def potato(self):
        print("potato is very good")
    def sayhi(self): #new method
        print(f"Hi my name is {self.name} and I work at {self.company}.")

In [ ]:
toy = Person("Toy")
john =Employee("John", "Google")
toy.sayhi()
john.sayhi()

Hi my name is Toy!
Hi my name is John and I work at Google.


In [ ]:
toy.hey()

Hello world


In [ ]:
john.hey()

Hello world


In [ ]:
john.potato()

potato is very good


In [ ]:
# try except block
try:
    1/0
except NameError:
    print("Variable is not found")
except ZeroDivisionError:
    print("cannot divide a number with zero")
except ValueError:
    print("Please check your data type again")
else:
    print("Done")
finally:
    print("this is last line")

cannot divide a number with zero
this is last line


In [ ]:
assert 1+1 == 5, "1+1 must be equal 2"

AssertionError: ignored

In [ ]:
def check_this(a,b):
    assert a+b > 10, "a+b should be more than 10"
    return a+b

In [ ]:
check_this(10,20)

30

In [ ]:
#type hint
def check_this(a: int,b: int) -> int:
    assert a+b > 10, "a+b should be more than 10"
    return a+b

In [ ]:
check_this(10,20)

30

In [ ]:
#lambda function

In [ ]:
def gretting(name):
    print("hello "+ name)

In [ ]:
greeting = lambda name: print("hello " + name)

In [ ]:
greeting("toy")

hello toy


In [ ]:
def odd_or_even(num):
    if num % 2 == 0:
        print("even")
    else:
        print("odd")

In [ ]:
odd_or_even = lambda num: "even" if num % 2 == 0 else "odd"

In [ ]:
odd_or_even(4)

'even'

In [ ]:
#list of colored balls
balls = ['red', 'red', 'green', 'blue', 'blue']

In [ ]:
def summary(lst_items):
    result = {} # empty dictionary
    for item in lst_items:
        if item in result:
            result[item] +=1
        else:
            result[item] = 1
    return(result)


In [ ]:
summary(balls)

{'red': 2, 'green': 1, 'blue': 2}

In [ ]:
# comma separated values(csv file)
# ! magic command

In [ ]:
!pwd

/content


In [ ]:
!ls sample_data/

anscombe.json		      mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md


In [ ]:
!rmdir newfolder

In [ ]:
!echo hello

hello


In [ ]:
!cat hotel.csv

id,hotel,location,price
1,Accor,Thailand,50
2,Ibis,Italy,60
3,London,UK,55
4,Seoul,Korea,45
5,le Concord,USA,66

In [ ]:
import csv #module

file = open("hotel.csv")

data = csv.reader(file)
for row in data:
    print(row)

file.close()

['\ufeffid', 'hotel', 'location', 'price']
['1', 'Accor', 'Thailand', '50']
['2', 'Ibis', 'Italy', '60']
['3', 'London', 'UK', '55']
['4', 'Seoul', 'Korea', '45']
['5', 'le Concord', 'USA', '66']


In [ ]:
# context manager
with open("hotel.csv", "r") as file:
    data = csv.reader(file)
    for row in data:
        print(row)

['\ufeffid', 'hotel', 'location', 'price']
['1', 'Accor', 'Thailand', '50']
['2', 'Ibis', 'Italy', '60']
['3', 'London', 'UK', '55']
['4', 'Seoul', 'Korea', '45']
['5', 'le Concord', 'USA', '66']


In [ ]:
# context manager
import csv
try:
    with open("hotel.csv", "r") as file:
        data = csv.reader(file)
        for row in data:
            print(row)
except:
    print("Found some errors, please check again")

['\ufeffid', 'hotel', 'location', 'price']
['1', 'Accor', 'Thailand', '50']
['2', 'Ibis', 'Italy', '60']
['3', 'London', 'UK', '55']
['4', 'Seoul', 'Korea', '45']
['5', 'le Concord', 'USA', '66']


In [ ]:
#context manager

csv_data = [] #empty list

with open("hotel.csv") as file:
    data = csv.reader(file)
    for row in data:
        csv_data.append(row)

print(csv_data)

[['\ufeffid', 'hotel', 'location', 'price'], ['1', 'Accor', 'Thailand', '50'], ['2', 'Ibis', 'Italy', '60'], ['3', 'London', 'UK', '55'], ['4', 'Seoul', 'Korea', '45'], ['5', 'le Concord', 'USA', '66']]


In [ ]:
import pandas as pd

df = pd.read_csv("hotel.csv")

df

id       hotel  location  price
0   1       Accor  Thailand     50
1   2        Ibis     Italy     60
2   3      London        UK     55
3   4       Seoul     Korea     45
4   5  le Concord       USA     66

In [ ]:
import pandas as pd

df = pd.read_csv("hotel.csv")

df["price_double"] = df["price"]*2 #create new column

df.to_csv("hotel_modified.csv")

In [ ]:
!cat hotel_modified.csv

,id,hotel,location,price,price_double
0,1,Accor,Thailand,50,100
1,2,Ibis,Italy,60,120
2,3,London,UK,55,110
3,4,Seoul,Korea,45,90
4,5,le Concord,USA,66,132


In [ ]:
# write csv file
import csv

headers = ["id", "name", "age"]
data = [
    [1, "toy", 25],
    [2, "win", 26],
    [3, "tip", 27]
]
with open("newfile.csv", "w") as file:
    writer = csv.writer(file)
    writer.writerow(headers)
    writer.writerows(data)

In [ ]:
!cat newfile.csv

id,name,age
1,toy,25
2,win,26
3,tip,27


In [ ]:
result = []
with open("newfile.csv") as file:
    data = csv.reader(file)
    for row in data:
        result.append(row)
    print(result)

[['id', 'name', 'age'], ['1', 'toy', '25'], ['2', 'win', '26'], ['3', 'tip', '27']]


In [ ]:
#regular expression

import re

text ="a duck walks into a bar"

re.search("duck", text)

<re.Match object; span=(2, 6), match='duck'>

In [ ]:
#regular expression

import re

text ="a tiger walks into a bar"

result = re.search("duck", text)

if result:
    print("Duck found")
else:
    print("Duck not found")

Duck not found


In [ ]:
# list comprehension
numbers = [1,2,3,4,5]

In [ ]:
result =[]
for num in numbers:
    result.append(num*2)
print(result)

[2, 4, 6, 8, 10]


In [ ]:
result =[num*2 for num in numbers]
print(result)

[2, 4, 6, 8, 10]


In [ ]:
# list comprehension
numbers = [1,2,3,4,5] #-> 2,4

In [ ]:
even_nums =[]

for num in numbers:
    if num % 2==0:
        even_nums.append(num)
print(even_nums)

[2, 4]


In [ ]:
odd_nums = [ num for num in numbers if num%2 ==1]
even_nums = [ num for num in numbers if num%2 ==0]

print(odd_nums, even_nums)

[1, 3, 5] [2, 4]


In [ ]:
## json => javascript Object Notation
!ls

sample_data  win.json


In [ ]:
import json

with open("win.json", "r") as file:
    data = json.load(file)

In [ ]:
data

{'name': 'win',
 'age': 38,
 'movie_lover': True,
 'movies': ['batman', 'superman']}

In [ ]:
data["age"]

38

In [ ]:
data["movies"][1]

'superman'

In [ ]:
#create new json file
school = {
    "name": "bootcamp",
    "batch": 7,
    "duration": "4 months",
}

with open("newjason.json", "w") as file:
    json.dump(school, file)

In [ ]:
!cat newjason.json

{"name": "bootcamp", "batch": 7, "duration": "4 months"}

In [ ]:
with open("newjason.json", "r") as file:
    data2 = json.load(file)

In [ ]:
data2

{'name': 'bootcamp', 'batch': 7, 'duration': '4 months'}

In [ ]:
#API get requests

#HW01 -find public API

import requests

url = "https://swapi.dev/api/people/45"

result = requests.get(url)

result.text

'{"name":"Bib Fortuna","height":"180","mass":"unknown","hair_color":"none","skin_color":"pale","eye_color":"pink","birth_year":"unknown","gender":"male","homeworld":"https://swapi.dev/api/planets/37/","films":["https://swapi.dev/api/films/3/"],"species":["https://swapi.dev/api/species/15/"],"vehicles":[],"starships":[],"created":"2014-12-20T09:47:02.512000Z","edited":"2014-12-20T21:17:50.407000Z","url":"https://swapi.dev/api/people/45/"}'

In [ ]:
result.status_code

200

In [ ]:
data_json = result.json()
data_json["name"]

'Bib Fortuna'

In [ ]:
#API get requests

#HW01 -find public API

from requests import get
from time import sleep

nums = list(range(1,6))
result =[]

for i in nums:
    url = f"https://swapi.dev/api/people/{i}" #1-5
    response = get(url)
    data =response.json()
    row = [data["name"],
           data["height"],
           data["mass"],
           data["gender"]
    ]
    result.append(row)
    sleep(1) #second
print(result)


[['Luke Skywalker', '172', '77', 'male'], ['C-3PO', '167', '75', 'n/a'], ['R2-D2', '96', '32', 'n/a'], ['Darth Vader', '202', '136', 'male'], ['Leia Organa', '150', '49', 'female']]


In [ ]:
list(range(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
import pandas as pd
df = pd.DataFrame(result, columns=["name", "height", "mass", "gender"])
df.to_csv("starwarapi.csv")

df

name height mass  gender
0  Luke Skywalker    172   77    male
1           C-3PO    167   75     n/a
2           R2-D2     96   32     n/a
3     Darth Vader    202  136    male
4     Leia Organa    150   49  female

Web scraping

In [ ]:
#webscraping
#gazpacho

# https://www.imdb.com/search/title/?groups=top_100&sort=user_rating,desc

In [ ]:
!pip list

Package                          Version
-------------------------------- ---------------------
absl-py                          1.4.0
aiohttp                          3.8.5
aiosignal                        1.3.1
alabaster                        0.7.13
albumentations                   1.2.1
altair                           4.2.2
anyio                            3.7.1
appdirs                          1.4.4
argon2-cffi                      21.3.0
argon2-cffi-bindings             21.2.0
array-record                     0.4.0
arviz                            0.15.1
astropy                          5.2.2
astunparse                       1.6.3
async-timeout                    4.0.2
attrs                            23.1.0
audioread                        3.0.0
autograd                         1.6.2
Babel                            2.12.1
backcall                         0.2.0
beautifulsoup4                   4.11.2
bleach                           6.0.0
blinker                          1.4
bl

In [ ]:
!pip install gazpacho

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for gazpacho: filename=gazpacho-1.1-py3-none-any.whl size=7462 sha256=8724fe4fc85a820e0926a2b08025301250912eb3aa8c2cf86180b93500d9d50a
  Stored in directory: /root/.cache/pip/wheels/9b/bf/9f/8c8849499462415fa5cdf0d9edb1103c189bdbece90c51488e
Successfully built gazpacho


In [ ]:
!pip list | grep "gaz"

gazpacho                         1.1


In [ ]:
from gazpacho import Soup
from requests import get

url = "https://www.imdb.com/search/title/?groups=top_100&sort=user_rating,desc"

response = get(url)

print(response.status_code)

200


In [ ]:
from gazpacho import Soup
from requests import get

url = "https://www.imdb.com/search/title/?groups=top_100&sort=user_rating,desc"

headers = {"Accept-Language": "en-US"} #request language

response = get(url, headers=headers)

imdb = Soup(response.text) #wrap with soup object

In [ ]:
type(imdb)

gazpacho.soup.Soup

In [ ]:
imdb.find("title")

[<title>IMDb &quot;Top 100&quot;
 (Sorted by IMDb Rating Descending) - IMDb</title>,
 <title>IMDb, an Amazon company</title>]

In [ ]:
imdb.find("title")[0].strip() #delete html tag

'IMDb "Top 100" (Sorted by IMDb Rating Descending) - IMDb'

In [ ]:
imdb.find("h3")[9].strip()

'10. Inception (2010)'

In [ ]:
title_list = imdb.find("h3", {"class": "lister-item-header"})

In [ ]:
for title in title_list:
    print(title.strip())

1. The Shawshank Redemption (1994)
2. The Godfather (1972)
3. The Dark Knight (2008)
4. Schindler's List (1993)
5. 12 Angry Men (1957)
6. The Lord of the Rings: The Return of the King (2003)
7. The Godfather Part II (1974)
8. Spider-Man: Across the Spider-Verse (2023)
9. Pulp Fiction (1994)
10. Inception (2010)
11. Fight Club (1999)
12. The Lord of the Rings: The Fellowship of the Ring (2001)
13. Forrest Gump (1994)
14. The Good, the Bad and the Ugly (1966)
15. The Lord of the Rings: The Two Towers (2002)
16. Oppenheimer (2023)
17. Interstellar (2014)
18. Goodfellas (1990)
19. One Flew Over the Cuckoo's Nest (1975)
20. The Matrix (1999)
21. Star Wars: Episode V - The Empire Strikes Back (1980)
22. Se7en (1995)
23. Saving Private Ryan (1998)
24. The Silence of the Lambs (1991)
25. Terminator 2: Judgment Day (1991)
26. The Green Mile (1999)
27. Star Wars: Episode IV - A New Hope (1977)
28. City of God (2002)
29. Spirited Away (2001)
30. Life Is Beautiful (1997)
31. Seven Samurai (1954)
3

In [ ]:
titles = [title.strip() for title in title_list]
print(titles)

['1. The Shawshank Redemption (1994)', '2. The Godfather (1972)', '3. The Dark Knight (2008)', "4. Schindler's List (1993)", '5. 12 Angry Men (1957)', '6. The Lord of the Rings: The Return of the King (2003)', '7. The Godfather Part II (1974)', '8. Spider-Man: Across the Spider-Verse (2023)', '9. Pulp Fiction (1994)', '10. Inception (2010)', '11. Fight Club (1999)', '12. The Lord of the Rings: The Fellowship of the Ring (2001)', '13. Forrest Gump (1994)', '14. The Good, the Bad and the Ugly (1966)', '15. The Lord of the Rings: The Two Towers (2002)', '16. Oppenheimer (2023)', '17. Interstellar (2014)', '18. Goodfellas (1990)', "19. One Flew Over the Cuckoo's Nest (1975)", '20. The Matrix (1999)', '21. Star Wars: Episode V - The Empire Strikes Back (1980)', '22. Se7en (1995)', '23. Saving Private Ryan (1998)', '24. The Silence of the Lambs (1991)', '25. Terminator 2: Judgment Day (1991)', '26. The Green Mile (1999)', '27. Star Wars: Episode IV - A New Hope (1977)', '28. City of God (200

In [ ]:
#pull runtime

runtimes =imdb.find("span", {"class": "runtime"})
print(runtimes)

[<span class="runtime">142 min</span>, <span class="runtime">175 min</span>, <span class="runtime">152 min</span>, <span class="runtime">195 min</span>, <span class="runtime">96 min</span>, <span class="runtime">201 min</span>, <span class="runtime">202 min</span>, <span class="runtime">140 min</span>, <span class="runtime">154 min</span>, <span class="runtime">148 min</span>, <span class="runtime">139 min</span>, <span class="runtime">178 min</span>, <span class="runtime">142 min</span>, <span class="runtime">178 min</span>, <span class="runtime">179 min</span>, <span class="runtime">180 min</span>, <span class="runtime">169 min</span>, <span class="runtime">145 min</span>, <span class="runtime">133 min</span>, <span class="runtime">136 min</span>, <span class="runtime">124 min</span>, <span class="runtime">127 min</span>, <span class="runtime">169 min</span>, <span class="runtime">118 min</span>, <span class="runtime">137 min</span>, <span class="runtime">189 min</span>, <span class=

In [ ]:
runtimes = [runtime.strip() for runtime in runtimes]
print(runtimes)

['142 min', '175 min', '152 min', '195 min', '96 min', '201 min', '202 min', '140 min', '154 min', '148 min', '139 min', '178 min', '142 min', '178 min', '179 min', '180 min', '169 min', '145 min', '133 min', '136 min', '124 min', '127 min', '169 min', '118 min', '137 min', '189 min', '121 min', '130 min', '125 min', '116 min', '207 min', '130 min', '133 min', '130 min', '116 min', '132 min', '155 min', '151 min', '117 min', '106 min', '110 min', '150 min', '106 min', '88 min', '119 min', '89 min', '112 min', '109 min', '102 min', '165 min']


In [ ]:
#combine 2 list to be one dataframe

data = [title, runtimes]

import pandas as pd
pd.DataFrame(data, columns = ["title", "runtime"])

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "title": titles,
    "runtime": runtimes
    })
df.head(5)

title  runtime
0  1. The Shawshank Redemption (1994)  142 min
1             2. The Godfather (1972)  175 min
2           3. The Dark Knight (2008)  152 min
3          4. Schindler's List (1993)  195 min
4              5. 12 Angry Men (1957)   96 min

In [ ]:
df.to_csv("imdb.csv")

Basic Data Tools
* numpy
* pandas
* sklearn

In [ ]:
#numpy -> numerical python
import numpy as np

num = [1,2,3,4,5]

num_arr = np.array(num)

num_arr*2

array([ 2,  4,  6,  8, 10])

In [ ]:
print(num_arr*2, num_arr+2, num_arr-2, num_arr/5)

[ 2  4  6  8 10] [3 4 5 6 7] [-1  0  1  2  3] [0.2 0.4 0.6 0.8 1. ]


In [ ]:
#statistical basic calculation
np.sum(num_arr)
np.mean(num_arr)
np.median(num_arr)
np.std(num_arr)
np.min(num_arr)
np.max(num_arr)
len(num_arr)

5

In [ ]:
num_arr.mean()

3.0

In [ ]:
num_arr.std()

1.4142135623730951

In [ ]:
#matrix 2d-array
m1 = np.array([
    [1,2],
    [3,4]
])

In [ ]:
m1*5

array([[ 5, 10],
       [15, 20]])

In [ ]:
m2 = np.array([
    [5,5],
    [4,2]
])

In [ ]:
print(m1, "\n"*2, m2)

[[1 2]
 [3 4]] 

 [[5 5]
 [4 2]]


In [ ]:
m1*m2

array([[ 5, 10],
       [12,  8]])

In [ ]:
#m1.dot(m2)
np.dot(m1,m2)

array([[13,  9],
       [31, 23]])

In [ ]:
#introduction to pandas
import pandas as pd
import numpy as np

In [ ]:
hotel = pd.read_csv("hotel.csv")

In [ ]:
hotel.shape #row,column

(5, 4)

In [ ]:
hotel.info() #pandas dataframe method

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   id        5 non-null      int64 
 1   hotel     5 non-null      object
 2   location  5 non-null      object
 3   price     5 non-null      int64 
dtypes: int64(2), object(2)
memory usage: 288.0+ bytes


In [ ]:
hotel.describe(include="all")

id  hotel  location      price
count   5.000000      5         5   5.000000
unique       NaN      5         5        NaN
top          NaN  Accor  Thailand        NaN
freq         NaN      1         1        NaN
mean    3.000000    NaN       NaN  55.200000
std     1.581139    NaN       NaN   8.228001
min     1.000000    NaN       NaN  45.000000
25%     2.000000    NaN       NaN  50.000000
50%     3.000000    NaN       NaN  55.000000
75%     4.000000    NaN       NaN  60.000000
max     5.000000    NaN       NaN  66.000000

In [ ]:
hotel["price"]

0    50
1    60
2    55
3    45
4    66
Name: price, dtype: int64

In [ ]:
hotel["vat"] = hotel["price"]* 0.07

#R version
# hotel$vat = hotel$price * 0.07

hotel

id       hotel  location  price   vat
0   1       Accor  Thailand     50  3.50
1   2        Ibis     Italy     60  4.20
2   3      London        UK     55  3.85
3   4       Seoul     Korea     45  3.15
4   5  le Concord       USA     66  4.62

In [ ]:
#query (filter rows)

value_hotel = hotel.query("price > 40")
value_hotel.to_csv("value_hotel.csv")
#r version

# hotel %>% filter(price>40)
# or
# filter(hotel, price > 40)

In [ ]:
#drop column
new_hotel = hotel.drop(["id", "vat"], axis=1)

In [ ]:
#inplace

hotel.drop("id", axis=1, inplace=True)
hotel

hotel  location  price
0       Accor  Thailand     50
1        Ibis     Italy     60
2      London        UK     55
3       Seoul     Korea     45
4  le Concord       USA     66

In [ ]:
#filter
hotel.query(" price < 60 and location == 'UK' ")

hotel location  price
2  London       UK     55

In [ ]:
# sklearn => machine learning most popular package
# template in sklearn to train_test_split

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
import pandas as pd


In [ ]:
mtcars = pd.read_csv("https://gist.githubusercontent.com/seankross/a412dfbd88b3db70b74b/raw/5f23f993cd87c283ce766e7ac6b329ee7cc2e1d1/mtcars.csv")

In [ ]:
mtcars.head()

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [ ]:
#prepare data

X = mtcars[["hp", "wt", "am"]]
y = mtcars["mpg"] #predicted

In [ ]:
#split data 80% train, 20% test

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)


In [ ]:
#train model
# model = LinearRegression().fit(X_train, y_train)
model = RandomForestRegressor()
model.fit(X_train, y_train)

#test model/scoring
pred = model.predict(X_test)

pred
#evaluate model


array([18.745, 12.05 , 15.463, 25.514, 21.943, 18.361, 14.774])

In [ ]:
#train model
model = RandomForestRegressor()
model.fit(X_train, y_train)
##model.fit(X_train, y_train)

#test model/scoring
pred = model.predict(X_test)

# mean absolute error
mae = np.mean(np.absolute(y_test - pred))
# mean square error
mse = np.mean((y_test - pred)**2)

print(mae, mse)


#evaluate model


2.2178571428571434 9.445430142857115


In [ ]:
#search algorithm 3 models and find out
#classification, regressor

In [ ]:
# r caret
model = train(y ~ x, data, method ="lm")
p = predict(model, newdata)